
import Navbar from "@/components/fixed/Navbar";
import "./globals.css";
import Footer from "@/components/fixed/Footer";



export const metadata = {
  title: "Ade portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-black">
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
